pre-commit:
  parallel: true
  commands:
    lint:
      run: bun run lint:fix
    typecheck:
      run: bun run typecheck

commit-msg:
  commands:
    commitlint:
      run: bunx commitlint --edit {1}